# Generated by Django 3.2.8 on 2021-12-04 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_request_type', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=3)),
                ('max_total_limit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry', models.DateField()),
                ('max_finance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_age_for_repayment', models.IntegerField()),
                ('minimum_period', models.IntegerField()),
                ('maximum_period', models.IntegerField()),
                ('minimum_amount_currency', models.CharField(max_length=3)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grace_period', models.IntegerField()),
                ('interest_type', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('model', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='transactions.workmodel')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.parties')),
                ('program_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.programtype')),
            ],
        ),
    ]
